config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'
  get '/about', to: 'home#about'

  resources :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, :description, presence: true
  validates :title, uniqueness: true
  validates :ranking, numericality: { only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
  end

  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if params[:search]
      @items = Item.where("title like ? ", "%#{params[:search]}%")
    else
      @items = Item.all
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(items_params)
    if @item.save
      # redirect_to item_path(@item.id)
      redirect_to @item  #redirect to show action
      flash[:success] = "Item #{@item.title} created!"
    else
      flash[:danger] = "Please fix the errors"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(items_params)
      redirect_to @item
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
    flash[:success] = "Item was deleted"
  end

  private

  def items_params
    params.require(:item).permit(:title, :description, :ranking, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/about.html.erb
<div class="row">
  <p>
    Global CSS settings,
    fundamental HTML elements styled and enhanced with extensible classes, and an advanced grid system.
  </p>
  <%= link_to 'Start', root_path, class: 'btn btn-lg btn-primary' %>
</div>

app/views/home/welcome.html.erb
<div class="jumbotron">
  <h1>Hello, stanger!</h1>
    <p>this is our amazing tool for adding complicated and impossbile todo. Please fell free to use it!.</p>
   <%= link_to 'Add new Todo', new_item_path, class: 'btn btn-info btn-lg' %>
   <%= link_to 'List all Todos', items_path, class: 'btn btn-success btn-lg' %>
   <%= link_to 'About Us', about_path, class: 'btn btn-default btn-lg' %>
</div>

app/views/items/edit.html.erb
<div class="col-lg9">
  <div class="page-header">
    <h1>Edit item!!</h1>
    <% if @item.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited
            this item from being saved:</h2>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="col-lg-5">
      <%= form_for @item, class: 'form-horizontal' do |f| %>
          <div class="form-group">
            <%= f.label :status  %>
            <%= f.select :status,[['Done', 1], ['Progress', 0]], class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit( class: 'btn btn-default') %>
          </div>
      <%end%>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="col-lg-10">
  <h2>All the items</h2>
  <span>Total items: <%= @items.count %></span>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Ranking</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @items.each_with_index do |item, index| %>
        <tr>
           <td>
             <%= index+ 1 %>
           </td>
          <td>
            <%= item.title %>
          </td>
          <td>
            <%= item.description %>
          </td>
          <td>
            <% if item.status %>
                <p><span class="label label-success">Progress</span></p>
            <%else%>
                <p><span class="label label-warning">Done</span></p>
            <%end%>
          </td>
          <td>
            <%= item.ranking %>
          </td>
          <td>
            <%= link_to 'edit', edit_item_path(item), class: 'btn btn-primary'%>
            <%= link_to 'show', item_path(item), class: 'btn btn-default'%>
            <%= link_to 'Delete', item_path(item), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default' %>          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="col-lg-6">
  <%= form_tag items_path, method: 'get' do %>
    <%= text_field_tag :search, params[:search] %>
     <%= submit_tag 'Search for items', class: 'btn btn-info' %>
  <%end%>
  <% if params[:search] %>
    <%= link_to 'Reset', items_path, class: 'btn btn-link' %>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="col-lg9">
  <div class="page-header">
    <h1>Add a new ITEM!!</h1>
    <% if @item.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited
            this item from being saved:</h2>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="col-lg-5">
      <%= form_for @item, class: 'form-horizontal' do |f| %>
          <div class="form-group">
            <%= f.label :title  %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description  %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :status  %>
            <%= f.select :status,[['Done', 1], ['Progress', 0]], class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :ranking  %>
            <%= f.text_field(:ranking,  class: 'form-control') %>
          </div>
          <div class="form-group">
            <%= f.submit( class: 'btn btn-default') %>
          </div>
      <%end%>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="col-lg-9">
  <div class="page-header">
    <%= @item.title %>
  </div>
  <% if @item.status %>
      <h3>Status:</h3>
      <h2><span class="label label-success">Done</span></h2>
  <%else%>
      <h3>Status:</h3>
      <h2><span class ="label label-warning">Progress</span></h2>
  <%end%>

 <div class="col-lg-8">
   <%= @item.description %>
 </div>
  <div class="col-lg-6">
    <%= time_ago_in_words @item.created_at %>
  </div>

  <div class="col-lg-9">
    <%= link_to 'all items', items_path, class: 'btn btn-primary' %>
    <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-info' %>
    <%= link_to 'Delete', item_path(@item), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>